version: "3"
services:
  nifi-auth:
    image: apache/nifi:1.15.0
    container_name: nifi-https
    restart: always
    ports:
      - "9556:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_PROXY_HOST=75.119.134.195:9556
